package aula;


import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/*
 * FrmJogo.java
 *
 * Created on 7 de Março de 2007, 19:52
 */
/**
 *
 * @author Glauco
 */
public class FrmJogo extends javax.swing.JFrame implements Runnable {

    private ArrayList<Bola> lixo = new ArrayList();
    private ArrayList<Bola> bolas = new ArrayList();

    /**
     * Creates new form FrmJogo
     */
    public FrmJogo() {
        initComponents();
        this.setSize(800, 600);
        createBufferStrategy(2);
        setIgnoreRepaint(true);
        Thread t = new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

    }//GEN-LAST:event_formKeyReleased

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
// TODO adicione seu código de manipulação aqui:
    }//GEN-LAST:event_formMouseMoved

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped

    }//GEN-LAST:event_formKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJogo().setVisible(true);
            }
        });
    }

    public void run() {

        inicarBolas();

        while (true) {

            Graphics g = getBufferStrategy().getDrawGraphics();

            //Limpa a Tela
            g.setColor(Color.WHITE);
            g.fillRect(0, 0, this.getWidth(), this.getHeight());

            //Move todas as bolas
            for (Bola b : bolas) {
                b.move();
            }

             //Desenha todas as bolas
            for (Bola b : bolas) {
                b.desenha(g);
            }

            //Verifica colisao entre bolas. Todas com todas
            for (Bola b1 : bolas) {
                for (Bola b2 : bolas) {
                    if (b1.colisao(b2)) {
                        lixo.add(b2);
                        b1.aumentarTamanho();
                    }
                }
            }

            Bola pri = bolas.get(0);
            boolean init = true;
            for(Bola b : bolas)
               if(!pri.getColor().equals(b.getColor()))
               {
                  init = false;
                  break;
               }
            
            if(init)
                inicarBolas();
            
                    
            
            
            
            bolas.removeAll(lixo);
            lixo.clear();
            
           
            //Verifica Colisao Bola com Formulario
            for (Bola b : bolas) {
                b.colisaoForm(getWidth(), getHeight());
            }

            
                    

            //Desenha na Tela
            g.dispose();
            getBufferStrategy().show();

            try {
                Thread.sleep(30);
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void inicarBolas() {
        int x, y;
        bolas.clear();
        

        for (int i = 0; i < 10; i++) {
            x = (int) (Math.random() * getWidth());
            y = (int) (Math.random() * getHeight());
            Bola b = new Bola(Color.RED, Color.GREEN);
            b.setX(x);
            b.setY(y);
            bolas.add(b);
        }
        
        for (int i = 0; i < 10; i++) {
            x = (int) (Math.random() * getWidth());
            y = (int) (Math.random() * getHeight());
            Bola b = new Bola(Color.GREEN, Color.BLUE);
            b.setX(x);
            b.setY(y);
            bolas.add(b);
        }

        for (int i = 0; i < 10; i++) {
            x = (int) (Math.random() * getWidth());
            y = (int) (Math.random() * getHeight());
            Bola b = new Bola(Color.BLUE, Color.RED);
            b.setX(x);
            b.setY(y);
            bolas.add(b);
        }
        
    }

}
